### ISSUE TITLE
Support Sassc

### ISSUE THREAD

**Issue by xcoulon** [patternfly/patternfly-sass#99]
Sassc is a wrapper for Libsass but I can't use it as a drop-in replacement of ruby-sass in awestruct because I get the following error:

```
An error during rendering /stylesheets/print.scss occurred.
While processing file /Users/xcoulon/code/beanvalidation.org/stylesheets/print.scss
An error occurred: Error: File to import not found or unreadable: patternfly
       Parent style sheet: /Users/xcoulon/code/beanvalidation.org/stylesheets/partials/_base.scss
        on line 1 of stylesheets/partials/_base.scss
>> @import "patternfly";
   ^

/Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/gems/sassc-1.8.4/lib/sassc/engine.rb:43:in `render'
/Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/gems/tilt-2.0.2/lib/tilt/sass.rb:17:in `evaluate'
/Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/gems/tilt-2.0.2/lib/tilt/template.rb:99:in `render'
/Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/bundler/gems/awestruct-0dbfd2ad2061/lib/awestruct/handlers/base_tilt_handler.rb:134:in `rendered_content'
/Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/bundler/gems/awestruct-0dbfd2ad2061/lib/awestruct/page.rb:143:in `rendered_content'
/Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/bundler/gems/awestruct-0dbfd2ad2061/lib/awestruct/engine.rb:389:in `generate_page'
/Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/bundler/gems/awestruct-0dbfd2ad2061/lib/awestruct/rack/generate.rb:35:in `call'
/Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
/Users/xcoulon/code/beanvalidation.org/.bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
/Users/xcoulon/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
/Users/xcoulon/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
/Users/xcoulon/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
Please see .awestruct/error.log for more information
```

Would it be possible to support Sassc in addition to rails and compass ?

**Comment by xcoulon** [comment]
FYI, @LightGuard provided me with https://github.com/xcoulon/beanvalidation.org/pull/1 as a workaround for now, but having something built-in would be much better.

**Comment by skateman** [comment]
@xcoulon as I see, SASSC has different `load_path`. I can't promise it to the next release which will come on Monday, but `3.2.0` will probably have the support.
